# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='spike.proto',
  package='',
  serialized_pb='\n\x0bspike.proto\"\xa3\x01\n\x07Request\x12\x0b\n\x03url\x18\x01 \x02(\t\x12\x12\n\nuser_agent\x18\x02 \x01(\t\x12\x1a\n\x12\x63ontent_type_limit\x18\x03 \x01(\t\x12\x15\n\rfetch_timeout\x18\x04 \x01(\x05\x12\x17\n\x0f\x63onnect_timeout\x18\x05 \x01(\x05\x12\x14\n\x0cparse_stream\x18\x06 \x01(\x08\x12\x15\n\rrecord_stream\x18\x07 \x01(\x08\"?\n\x04Task\x12\n\n\x02id\x18\x01 \x02(\x03\x12\x19\n\x07request\x18\x02 \x01(\x0b\x32\x08.Request\x12\x10\n\x08\x63onsumer\x18\x03 \x01(\t\"p\n\nTaskAction\x12\"\n\x06\x61\x63tion\x18\x01 \x02(\x0e\x32\x12.TaskAction.Action\x12\x13\n\x04task\x18\x02 \x02(\x0b\x32\x05.Task\")\n\x06\x41\x63tion\x12\x07\n\x03PUT\x10\x01\x12\n\n\x06\x43\x41NCEL\x10\x02\x12\n\n\x06REMOVE\x10\x03\".\n\x0c\x41\x63tionResult\x12\x0f\n\x07task_id\x18\x01 \x02(\x03\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\xd3\x02\n\nTaskResult\x12\x0f\n\x07task_id\x18\x01 \x02(\x03\x12\x1e\n\x04type\x18\x02 \x02(\x0e\x32\x10.TaskResult.Type\x12\x11\n\ttimestamp\x18\x03 \x02(\x03\x12\r\n\x05\x65rror\x18\x04 \x01(\x05\x12\x0c\n\x04meta\x18\x05 \x01(\t\x12\x13\n\x0bstatus_code\x18\x06 \x01(\x05\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\x0c\x12\x0f\n\x07headers\x18\x08 \x03(\t\x12\x11\n\tstripe_id\x18\t \x01(\x05\x12\x15\n\rstripe_offset\x18\n \x01(\x03\x12\x16\n\x0estripe_written\x18\x0b \x01(\x05\x12\x12\n\ncompressed\x18\x10 \x01(\x08\x12\x12\n\nerror_text\x18\x11 \x01(\t\"C\n\x04Type\x12\x0c\n\x08RESPONSE\x10\x01\x12\t\n\x05\x45RROR\x10\x02\x12\x0f\n\x0bSTREAM_META\x10\x03\x12\x11\n\rSTRIPE_COMMIT\x10\x04\"x\n\x0e\x42rokerResponse\x12&\n\x06status\x18\x01 \x02(\x0e\x32\x16.BrokerResponse.Status\x12\x13\n\x04task\x18\x02 \x01(\x0b\x32\x05.Task\")\n\x06Status\x12\x06\n\x02OK\x10\x01\x12\x08\n\x04TASK\x10\x02\x12\r\n\tTASK_GONE\x10\x03')



_TASKACTION_ACTION = descriptor.EnumDescriptor(
  name='Action',
  full_name='TaskAction.Action',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='PUT', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='CANCEL', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='REMOVE', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=317,
  serialized_end=358,
)

_TASKRESULT_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='TaskResult.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='RESPONSE', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STREAM_META', index=2, number=3,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='STRIPE_COMMIT', index=3, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=681,
  serialized_end=748,
)

_BROKERRESPONSE_STATUS = descriptor.EnumDescriptor(
  name='Status',
  full_name='BrokerResponse.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='OK', index=0, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TASK', index=1, number=2,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='TASK_GONE', index=2, number=3,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=829,
  serialized_end=870,
)


_REQUEST = descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='url', full_name='Request.url', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='user_agent', full_name='Request.user_agent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content_type_limit', full_name='Request.content_type_limit', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='fetch_timeout', full_name='Request.fetch_timeout', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='connect_timeout', full_name='Request.connect_timeout', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='parse_stream', full_name='Request.parse_stream', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='record_stream', full_name='Request.record_stream', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=16,
  serialized_end=179,
)


_TASK = descriptor.Descriptor(
  name='Task',
  full_name='Task',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='id', full_name='Task.id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='request', full_name='Task.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='consumer', full_name='Task.consumer', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=181,
  serialized_end=244,
)


_TASKACTION = descriptor.Descriptor(
  name='TaskAction',
  full_name='TaskAction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='action', full_name='TaskAction.action', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task', full_name='TaskAction.task', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASKACTION_ACTION,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=246,
  serialized_end=358,
)


_ACTIONRESULT = descriptor.Descriptor(
  name='ActionResult',
  full_name='ActionResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='task_id', full_name='ActionResult.task_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='ActionResult.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=360,
  serialized_end=406,
)


_TASKRESULT = descriptor.Descriptor(
  name='TaskResult',
  full_name='TaskResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='task_id', full_name='TaskResult.task_id', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='type', full_name='TaskResult.type', index=1,
      number=2, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='TaskResult.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error', full_name='TaskResult.error', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='meta', full_name='TaskResult.meta', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='status_code', full_name='TaskResult.status_code', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='content', full_name='TaskResult.content', index=6,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='headers', full_name='TaskResult.headers', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stripe_id', full_name='TaskResult.stripe_id', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stripe_offset', full_name='TaskResult.stripe_offset', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stripe_written', full_name='TaskResult.stripe_written', index=10,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='compressed', full_name='TaskResult.compressed', index=11,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='error_text', full_name='TaskResult.error_text', index=12,
      number=17, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _TASKRESULT_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=409,
  serialized_end=748,
)


_BROKERRESPONSE = descriptor.Descriptor(
  name='BrokerResponse',
  full_name='BrokerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='status', full_name='BrokerResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='task', full_name='BrokerResponse.task', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _BROKERRESPONSE_STATUS,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=750,
  serialized_end=870,
)

_TASK.fields_by_name['request'].message_type = _REQUEST
_TASKACTION.fields_by_name['action'].enum_type = _TASKACTION_ACTION
_TASKACTION.fields_by_name['task'].message_type = _TASK
_TASKACTION_ACTION.containing_type = _TASKACTION;
_TASKRESULT.fields_by_name['type'].enum_type = _TASKRESULT_TYPE
_TASKRESULT_TYPE.containing_type = _TASKRESULT;
_BROKERRESPONSE.fields_by_name['status'].enum_type = _BROKERRESPONSE_STATUS
_BROKERRESPONSE.fields_by_name['task'].message_type = _TASK
_BROKERRESPONSE_STATUS.containing_type = _BROKERRESPONSE;
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Task'] = _TASK
DESCRIPTOR.message_types_by_name['TaskAction'] = _TASKACTION
DESCRIPTOR.message_types_by_name['ActionResult'] = _ACTIONRESULT
DESCRIPTOR.message_types_by_name['TaskResult'] = _TASKRESULT
DESCRIPTOR.message_types_by_name['BrokerResponse'] = _BROKERRESPONSE

class Request(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _REQUEST
  
  # @@protoc_insertion_point(class_scope:Request)

class Task(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASK
  
  # @@protoc_insertion_point(class_scope:Task)

class TaskAction(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKACTION
  
  # @@protoc_insertion_point(class_scope:TaskAction)

class ActionResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ACTIONRESULT
  
  # @@protoc_insertion_point(class_scope:ActionResult)

class TaskResult(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _TASKRESULT
  
  # @@protoc_insertion_point(class_scope:TaskResult)

class BrokerResponse(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _BROKERRESPONSE
  
  # @@protoc_insertion_point(class_scope:BrokerResponse)

# @@protoc_insertion_point(module_scope)
